//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mozlite.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mozlite.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数&apos;{0}&apos;不能为空。 的本地化字符串。
        /// </summary>
        internal static string ArgumentIsEmpty {
            get {
                return ResourceManager.GetString("ArgumentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数&apos;{1}&apos;的&apos;{0}&apos;属性不能为空。 的本地化字符串。
        /// </summary>
        internal static string ArgumentPropertyNull {
            get {
                return ResourceManager.GetString("ArgumentPropertyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string ArgumentStatus_Completed {
            get {
                return ResourceManager.GetString("ArgumentStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        internal static string ArgumentStatus_Disabled {
            get {
                return ResourceManager.GetString("ArgumentStatus_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string ArgumentStatus_Failured {
            get {
                return ResourceManager.GetString("ArgumentStatus_Failured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string ArgumentStatus_Normal {
            get {
                return ResourceManager.GetString("ArgumentStatus_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览文件 的本地化字符串。
        /// </summary>
        internal static string BrowserTitle {
            get {
                return ResourceManager.GetString("BrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数&apos;{0}&apos;集合最少需要包含一个值。 的本地化字符串。
        /// </summary>
        internal static string CollectionArgumentIsEmpty {
            get {
                return ResourceManager.GetString("CollectionArgumentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你，你已经成功添加了“{0}”。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Created {
            get {
                return ResourceManager.GetString("DataAction_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，添加“{0}”失败了。 的本地化字符串。
        /// </summary>
        internal static string DataAction_CreatedFailured {
            get {
                return ResourceManager.GetString("DataAction_CreatedFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你，你已经成功删除了所选择的{0}。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Deleted {
            get {
                return ResourceManager.GetString("DataAction_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，删除“{0}”失败了。 的本地化字符串。
        /// </summary>
        internal static string DataAction_DeletedFailured {
            get {
                return ResourceManager.GetString("DataAction_DeletedFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，删除“{0}”失败了，因为包含的子项不为空。 的本地化字符串。
        /// </summary>
        internal static string DataAction_DeletedFailuredItemsNotEmpty {
            get {
                return ResourceManager.GetString("DataAction_DeletedFailuredItemsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，“{0}”已经存在，操作失败。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Duplicate {
            get {
                return ResourceManager.GetString("DataAction_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你，你已经成功完成了“{0}”。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Success {
            get {
                return ResourceManager.GetString("DataAction_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，发生了未知错误，操作失败，请重试。 的本地化字符串。
        /// </summary>
        internal static string DataAction_UnknownError {
            get {
                return ResourceManager.GetString("DataAction_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你，你已经成功更新了“{0}”。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Updated {
            get {
                return ResourceManager.GetString("DataAction_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，更新“{0}”失败了。 的本地化字符串。
        /// </summary>
        internal static string DataAction_UpdatedFailured {
            get {
                return ResourceManager.GetString("DataAction_UpdatedFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MM月dd日 的本地化字符串。
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 天前 的本地化字符串。
        /// </summary>
        internal static string DaysBefore {
            get {
                return ResourceManager.GetString("DaysBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;添加错误，因为已经存在一个同样名称的扩展属性。 的本地化字符串。
        /// </summary>
        internal static string DuplicateAnnotation {
            get {
                return ResourceManager.GetString("DuplicateAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 小时前 的本地化字符串。
        /// </summary>
        internal static string HoursBefore {
            get {
                return ResourceManager.GetString("HoursBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 &apos;{1}&apos;的实体类型&apos;{0}&apos;必须是一个引用类型。 的本地化字符串。
        /// </summary>
        internal static string InvalidEntityType {
            get {
                return ResourceManager.GetString("InvalidEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性表达式&apos;{0}&apos;不正确， 表达式必须提供一种属性访问，如： &apos;t =&gt; t.MyProperty&apos;；如果式多个属性，需要如下代码表示：&apos;t =&gt; new {{ t.MyProperty1, t.MyProperty2 }}&apos;。 的本地化字符串。
        /// </summary>
        internal static string InvalidPropertiesExpression {
            get {
                return ResourceManager.GetString("InvalidPropertiesExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性表达式&apos;{0}&apos;不正确， 表达式必须提供一种属性访问，如： &apos;t =&gt; t.MyProperty&apos;。 的本地化字符串。
        /// </summary>
        internal static string InvalidPropertyExpression {
            get {
                return ResourceManager.GetString("InvalidPropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刚刚 的本地化字符串。
        /// </summary>
        internal static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传路径不正确，当前文件所属实例不明确。 的本地化字符串。
        /// </summary>
        internal static string MediaFileUploadPathIsError {
            get {
                return ResourceManager.GetString("MediaFileUploadPathIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据迁移出错：{0}。 的本地化字符串。
        /// </summary>
        internal static string MigrationError {
            get {
                return ResourceManager.GetString("MigrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 分钟前 的本地化字符串。
        /// </summary>
        internal static string MunitesBefore {
            get {
                return ResourceManager.GetString("MunitesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{1}”的属性“{0}”必须包含get访问器。 的本地化字符串。
        /// </summary>
        internal static string NoGetter {
            get {
                return ResourceManager.GetString("NoGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{1}”的属性“{0}”必须包含set访问器。 的本地化字符串。
        /// </summary>
        internal static string NoSetter {
            get {
                return ResourceManager.GetString("NoSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}页 的本地化字符串。
        /// </summary>
        internal static string NumberPage {
            get {
                return ResourceManager.GetString("NumberPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择文件后在进行上传。 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectFirstAndThenUpload {
            get {
                return ResourceManager.GetString("PleaseSelectFirstAndThenUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表格的主键已经设置过了，不能重复设置。 的本地化字符串。
        /// </summary>
        internal static string PrimaryKeyIsAlreadySetted {
            get {
                return ResourceManager.GetString("PrimaryKeyIsAlreadySetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节大小必须能被 8 整除。 的本地化字符串。
        /// </summary>
        internal static string RandomNumberGenerator_SizeInvalid {
            get {
                return ResourceManager.GetString("RandomNumberGenerator_SizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员 的本地化字符串。
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对数据库中某些列进行分词，生成搜索需求文档，提供前天搜索服务。 的本地化字符串。
        /// </summary>
        internal static string Task_Searching_Description {
            get {
                return ResourceManager.GetString("Task_Searching_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索引擎服务 的本地化字符串。
        /// </summary>
        internal static string Task_Searching_Name {
            get {
                return ResourceManager.GetString("Task_Searching_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [服务]{0}执行错误：{1}。 的本地化字符串。
        /// </summary>
        internal static string TaskExecuteError {
            get {
                return ResourceManager.GetString("TaskExecuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在“{1}”找不到“{0}”的操作符。 的本地化字符串。
        /// </summary>
        internal static string UnknownOperation {
            get {
                return ResourceManager.GetString("UnknownOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体“{0}”不支持递归查询。 的本地化字符串。
        /// </summary>
        internal static string UnsupportedRecurse {
            get {
                return ResourceManager.GetString("UnsupportedRecurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型&apos;{0}&apos;暂时还不支持。 的本地化字符串。
        /// </summary>
        internal static string UnsupportedType {
            get {
                return ResourceManager.GetString("UnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件失败，请重试。 的本地化字符串。
        /// </summary>
        internal static string UploadFailured {
            get {
                return ResourceManager.GetString("UploadFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经成功上传了文件。 的本地化字符串。
        /// </summary>
        internal static string UploadSuccess {
            get {
                return ResourceManager.GetString("UploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy年MM月dd日 的本地化字符串。
        /// </summary>
        internal static string YearDateFormat {
            get {
                return ResourceManager.GetString("YearDateFormat", resourceCulture);
            }
        }
    }
}
